api_key: DEMO_KEY
ntfyTopic: dsiBuildSoftSummative
plot_config:
  color: blue
  title: Summary of Subcategories
  xlabel: Subcategories
  ylabel: Total Studies
  sizeH: 5
  sizeW: 6
output_paths: ['test']
verbose_log: FALSE
