plot_config:
  color: orange
  title: Summary of NASA Subcategories
  xlabel: Subcategories
  ylabel: Total Number of Studies
  sizeH: 5
  sizeW: 6
output_paths: ['unit_test_png']
verbose_log: FALSE

