api_key: DEMO_KEY
ntfyTopic: dsiBuildSoftSummative
plot_config:
  color: blue
  title: Summary of NASA studies categlories
  xlabel: NASA Studies Categories
  ylabel: Number of Studies
  sizeH: 2
  sizeW: 4
output_paths: ['my_plot', 'figure']
verbose_log: FALSE

