api_key: DEMO_KEY
verbose_log: FALSE
plot_config:
  title: Summary of NASA studies categlories
  xlabel: NASA Studies Categories
  ylabel: Persons
output_paths: ['my_plot']
ntfy: https://ntfy.sh/dsiBuildSoftSummative