api_key: DEMO_KEY
ntfyTopic: dsi_c2_brs
plot_config:
  color: blue
  title: Summary of Categories
  xlabel: Categories
  ylabel: Total
  sizeH: 5
  sizeW: 6
output_paths: ['figure']
verbose_log: FALSE
