api_key: DEMO_KEY
ntfyTopic: dsi_c2_brs
plot_config:
  color: red
  title: Summary of Categories
  xlabel: Categories
  ylabel: Total
  sizeH: 2
  sizeW: 4
output_paths: ['figure']
verbose_log: FALSE
