api_key: DEMO_KEY
ntfyTopic: dsiBuildSoftSummative
plot_config:
  color: red
  title: Summary of Studies Categories
  xlabel: Studies Categories Categories
  ylabel: Total Count
  size: 1
output_paths: ['plot']s
verbose_log: FALSE